name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "PWD: $(pwd)"
          ls -la

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'  # lockfile is in current dir

      - name: Install deps
        run: npm ci --no-optional

      - name: Run linter
        run: npm run lint
